
INSERT INTO `users`
    (`id`, `name`, `userid`, `passwd`, `real_email`, `fake_email`, `url`, `stories`, `mode`, `sort`, `threshold`, `bio`, `theme`, `signature`, `last_access`, `last_host`, `permissions`, `status`, `history`, `hash`, `timezone`)
VALUES
    (1,'','admin','*DDFB542AA0BD1D251995D81AEBEB96DEEAD1132F','admin@example.com','','',10,'',0,0,NULL,'','',NULL,'',0,1,NULL,'9e10edfbcb6b',NULL);


INSERT INTO `stories`
    (`id`, `author`, `subject`, `abstrakt`, `updates`, `article`, `category`, `department`, `timestamp`, `score`, `votes`, `status`)
VALUES
    (1,1,'How artificial intelligence is reshaping everyday life','Artificial intelligence has become an essential part of everyday life, seamlessly embedded in homes, workplaces, and public spaces. Smart assistants, powered by advanced natural language processing, understand context and intent, making interactions more intuitive and productive.',NULL,'Artificial intelligence has become an essential part of everyday life, seamlessly embedded in homes, workplaces, and public spaces. Smart assistants, powered by advanced natural language processing, understand context and intent, making interactions more intuitive and productive. AI-driven automation handles routine tasks, freeing people to focus on creativity and problem-solving.

In healthcare, AI systems analyze vast datasets to assist in diagnostics, personalize treatment plans, and predict outbreaks. Doctors and researchers rely on machine learning models to identify patterns that were previously undetectable, leading to earlier interventions and improved patient outcomes. AI-powered robots and virtual nurses provide support, especially in underserved areas.

Education has been transformed by adaptive learning platforms that tailor content to individual students’ needs and learning styles. AI tutors offer real-time feedback, helping learners overcome challenges and stay motivated. Teachers use analytics to track progress and adjust their methods, ensuring that no student is left behind.

Businesses leverage AI for data-driven decision-making, customer service, and supply chain optimization. Predictive analytics help companies anticipate market trends, while chatbots and virtual agents provide instant support. AI also plays a crucial role in cybersecurity, detecting threats and responding to incidents faster than ever before.

As AI’s influence grows, ethical considerations have become central to its development and deployment. Policymakers, technologists, and communities collaborate to address issues like bias, transparency, and privacy. The focus is on building trustworthy AI systems that respect human values, ensuring that technological progress benefits society as a whole.','Science','',0,0,0,2),
    (2,1,'The enduring magic of Glastonbury','Glastonbury delivered another unforgettable chapter in the festival’s storied history, drawing music lovers from around the globe to Somerset’s iconic Worthy Farm. Each edition was marked by a diverse and electrifying lineup, with headline performances from both legendary acts and rising stars.',NULL,'Glastonbury delivered another unforgettable chapter in the festival’s storied history, drawing music lovers from around the globe to Somerset’s iconic Worthy Farm. Each edition was marked by a diverse and electrifying lineup, with headline performances from both legendary acts and rising stars. The Pyramid Stage saw a triumphant return of classic rock icons, while the Other Stage pulsed with the energy of cutting-edge electronic and hip-hop artists, ensuring there was something for every musical taste.

Beyond the music, Glastonbury continued its tradition of championing sustainability and community spirit. Festival organizers introduced new eco-friendly initiatives, including expanded recycling programs and innovative renewable energy solutions powering much of the site. Attendees embraced these efforts, making the festival one of the greenest yet.

Art installations and immersive experiences dotted the landscape, transforming fields into vibrant galleries and interactive playgrounds. Workshops, talks, and wellness activities offered festival-goers opportunities for reflection and connection, reinforcing Glastonbury’s reputation as more than just a music festival—it’s a celebration of creativity, activism, and togetherness.

As the sun set on another magical weekend, Glastonbury left attendees with lasting memories and a renewed sense of hope, proving once again why it remains the world’s most beloved festival.','Entertainment','',0,0,0,2),
    (3,1,'Arsenal''s return to the summit','Arsenal won the 2025/2026 Premier League and ended a 22-year wait for the championship through patient rebuilding, tactical clarity, and a squad that learned how to handle the pressure of a title race.',NULL,'Arsenal won the 2025/2026 Premier League and ended a 22-year wait for the championship. Years of investment in young players, modern recruitment, and a clear footballing identity produced a team capable of sustaining a challenge from the opening weeks to the final run-in.

The side combined disciplined possession with aggressive pressing and a defence built to control matches. Established leaders guided a core that had developed together, while competition for places ensured that injuries and fixture congestion did not derail the campaign. Victories against direct rivals strengthened belief throughout the club.

The title also reflected the bond between the team and its supporters. The Emirates became an intense venue, and away support helped the players recover from setbacks. Arsenal returned to the summit through sustained planning, tactical evolution, and faith in a group that turned promise into achievement.','Sport','',0,0,0,2),
    (4,1,'The global rise of Nollywood','Nollywood has grown from a resourceful home-video industry into one of the world’s most energetic centres of film and television, building a vast audience through distinctly Nigerian stories.',NULL,'Nollywood has grown from a resourceful home-video industry into one of the world’s most energetic centres of film and television. Early filmmakers worked with limited budgets and direct distribution networks, yet created stories about family, ambition, faith, comedy, romance, and social change that audiences recognised immediately.

Films circulated across Africa and the diaspora, giving viewers characters, languages, and settings often absent from imported entertainment. The industry created opportunities for actors, writers, technicians, designers, musicians, and entrepreneurs while showing that popular culture could also be a major source of employment.

Digital production and streaming expanded Nollywood’s reach. Larger budgets, stronger cinematography, and international partnerships now sit alongside its fast independent sector. Its creative influence is undeniable: local stories told with confidence and imagination continue to travel far beyond Nigeria.','Entertainment','',0,0,0,2),
    (5,1,'Poland''s transformation into a European leader','Since the fall of communism, Poland has transformed its economy, strengthened its institutions, and become an increasingly influential member of the European Union.',NULL,'Since the fall of communism, Poland has undergone one of Europe’s most significant political and economic transformations. The transition from central planning was difficult, but it released entrepreneurial energy, connected businesses with international markets, and supported a growing services sector.

European Union membership accelerated the process. Investment in roads, railways, cities, universities, and digital infrastructure improved connections, while Polish companies became important parts of European supply chains. Workers and students gained opportunities to build experience across the continent and bring skills and ideas home.

Poland’s population, strategic location, and commitment to regional security have also increased its influence. Challenges remain in public services, regional inequality, and institutional trust, but the distance travelled is remarkable. Poland has emerged as a resilient economy and a leading state whose choices will help define Europe’s future.','News','',0,0,0,2);
