INSERT INTO `users`
    (`id`, `name`, `userid`, `passwd`, `real_email`, `fake_email`, `url`, `nodes`, `mode`, `sort`, `threshold`, `bio`, `theme`, `signature`, `last_access`, `last_host`, `status`, `hash`, `rating`, `timezone`, `language`, `role`)
VALUES
    (1,'','admin','*DDFB542AA0BD1D251995D81AEBEB96DEEAD1132F','admin@example.com','','',10,1,0,0,NULL,'','',NULL,'',2,'9e10edfbcb6b', NULL,NULL, 'en', '');


INSERT INTO `node`
    (`lid`, `type`, `title`, `status`, `author`)
VALUES
    (1, 'story', 'How artificial intelligence is reshaping everyday life', 3, 1);

INSERT INTO `node`
    (`lid`, `type`, `title`, `status`, `author`)
VALUES
    (2, 'story', 'The enduring magic of Glastonbury', 3,1);


INSERT INTO `story`
    (`nid`, `abstrakt`, `body`)
VALUES
    (1, 'Artificial intelligence is deeply integrated into daily life, powering personalized services, automating complex tasks, and enhancing decision-making across industries. Advances in natural language processing, computer vision, and ethical frameworks have made AI more accessible, trustworthy, and collaborative, driving innovation while raising important questions about privacy, bias, and human-AI interaction.','<p>Artificial intelligence has become an essential part of everyday life, seamlessly embedded in homes, workplaces, and public spaces. Smart assistants, powered by advanced natural language processing, understand context and intent, making interactions more intuitive and productive. AI-driven automation handles routine tasks, freeing people to focus on creativity and problem-solving.</p> <p>In healthcare, AI systems analyze vast datasets to assist in diagnostics, personalize treatment plans, and predict outbreaks. Doctors and researchers rely on machine learning models to identify patterns that were previously undetectable, leading to earlier interventions and improved patient outcomes. AI-powered robots and virtual nurses provide support, especially in underserved areas.</p> <p>Education has been transformed by adaptive learning platforms that tailor content to individual students’ needs and learning styles. AI tutors offer real-time feedback, helping learners overcome challenges and stay motivated. Teachers use analytics to track progress and adjust their methods, ensuring that no student is left behind.</p> <p>Businesses leverage AI for data-driven decision-making, customer service, and supply chain optimization. Predictive analytics help companies anticipate market trends, while chatbots and virtual agents provide instant support. AI also plays a crucial role in cybersecurity, detecting threats and responding to incidents faster than ever before.</p> <p>As AI’s influence grows, ethical considerations have become central to its development and deployment. Policymakers, technologists, and communities collaborate to address issues like bias, transparency, and privacy. The focus is on building trustworthy AI systems that respect human values, ensuring that technological progress benefits society as a whole.</p>');


INSERT INTO `story`
    (`nid`, `abstrakt`, `body`)
VALUES
    (2,'Glastonbury dazzled with legendary performances, groundbreaking art installations, and a vibrant celebration of music, culture, and sustainability.','<p>Glastonbury delivered another unforgettable chapter in the festival’s storied history, drawing music lovers from around the globe to Somerset’s iconic Worthy Farm. Each edition was marked by a diverse and electrifying lineup, with headline performances from both legendary acts and rising stars. The Pyramid Stage saw a triumphant return of classic rock icons, while the Other Stage pulsed with the energy of cutting-edge electronic and hip-hop artists, ensuring there was something for every musical taste.</p> <p>Beyond the music, Glastonbury continued its tradition of championing sustainability and community spirit. Festival organizers introduced new eco-friendly initiatives, including expanded recycling programs and innovative renewable energy solutions powering much of the site. Attendees embraced these efforts, making the festival one of the greenest yet.</p> <p>Art installations and immersive experiences dotted the landscape, transforming fields into vibrant galleries and interactive playgrounds. Workshops, talks, and wellness activities offered festival-goers opportunities for reflection and connection, reinforcing Glastonbury’s reputation as more than just a music festival—it’s a celebration of creativity, activism, and togetherness.</p> <p>As the sun set on another magical weekend, Glastonbury left attendees with lasting memories and a renewed sense of hope, proving once again why it remains the world’s most beloved festival.</p>');

INSERT INTO `node` (`lid`, `type`, `title`, `status`, `author`) VALUES
    (3, 'story', 'Arsenal''s return to the summit', 3, 1),
    (4, 'story', 'The global rise of Nollywood', 3, 1),
    (5, 'story', 'Poland''s transformation into a European leader', 3, 1);

INSERT INTO `story` (`nid`, `abstrakt`, `body`) VALUES
    (3,'Arsenal won the 2025/2026 Premier League and ended a 22-year wait through patient rebuilding, tactical clarity, and a squad ready for the pressure of a title race.','<p>Arsenal won the 2025/2026 Premier League and ended a 22-year wait for the championship. Years of investment in young players, modern recruitment, and a clear identity produced a team capable of sustaining a challenge from the opening weeks to the final run-in.</p> <p>The side combined disciplined possession with aggressive pressing and a defence built to control matches. Leaders guided a core that had developed together, while competition for places ensured injuries did not derail the campaign. Victories against direct rivals strengthened belief.</p> <p>The title reflected the bond between team and supporters. The Emirates became an intense venue, and away support helped the players recover from setbacks. Arsenal returned to the summit through planning, tactical evolution, and faith in a group that turned promise into achievement.</p>'),
    (4,'Nollywood has grown from a resourceful home-video industry into one of the world’s most energetic centres of film and television.','<p>Nollywood has grown from a resourceful home-video industry into one of the world’s most energetic centres of film and television. Early filmmakers worked with limited budgets and direct distribution, yet created stories that audiences recognised immediately.</p> <p>Films circulated across Africa and the diaspora, giving viewers characters, languages, and settings often absent from imported entertainment. The industry created opportunities for actors, writers, technicians, designers, musicians, and entrepreneurs.</p> <p>Digital production and streaming expanded Nollywood’s reach. Larger budgets, stronger cinematography, and international partnerships now sit alongside its independent sector. Local stories told with confidence and imagination continue to travel far beyond Nigeria.</p>'),
    (5,'Since the fall of communism, Poland has transformed its economy and become an increasingly influential member of the European Union.','<p>Since the fall of communism, Poland has undergone one of Europe’s most significant transformations. The transition from central planning released entrepreneurial energy, connected businesses with international markets, and supported a growing services sector.</p> <p>European Union membership accelerated the process. Investment in transport, cities, universities, and digital infrastructure improved connections, while Polish companies became important parts of European supply chains.</p> <p>Poland’s population, strategic location, and commitment to regional security increased its influence. Challenges remain, but the distance travelled is remarkable. Poland has emerged as a resilient economy and a leading state whose choices will help define Europe’s future.</p>');
