INSERT INTO users
    (`uid`, `name`, `pass`, `mail`, `mode`, `sort`, `threshold`, `created`, `status`, `timezone`, `init`, `data`)
VALUES
    (1,'admin', 'd41e98d1eafa6d6011d3a70f1a5b92f0', 'admin@example.com', 0, 0, 0, UNIX_TIMESTAMP(), 1, 0, 'admin@example.com', 'a:0:{}');

INSERT INTO `node`
VALUES
    (1,1,'story','How artificial intelligence is reshaping everyday life',1,1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),2,1,0,0),
    (2,2,'story','The enduring magic of Glastonbury',1,1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),2,1,0,0);

INSERT INTO `node_revisions`
VALUES
    (1,1,1,'How artificial intelligence is reshaping everyday life','<p><img src="/showcase-images/ai.jpg" alt="A robotic hand reaching towards an artificial intelligence network" width="1200" height="675" style="display:block;max-width:100%;height:auto;margin-bottom:1.5em"></p>Artificial intelligence has become an essential part of everyday life, seamlessly embedded in homes, workplaces, and public spaces. Smart assistants, powered by advanced natural language processing, understand context and intent, making interactions more intuitive and productive. AI-driven automation handles routine tasks, freeing people to focus on creativity and problem-solving.\r\n\r\nIn healthcare, AI systems analyze vast datasets to assist in diagnostics, personalize treatment plans, and predict outbreaks. Doctors and researchers rely on machine learning models to identify patterns that were previously undetectable, leading to earlier interventions and improved patient outcomes. AI-powered robots and virtual nurses provide support, especially in underserved areas.\r\n\r\nEducation has been transformed by adaptive learning platforms that tailor content to individual students’ needs and learning styles. AI tutors offer real-time feedback, helping learners overcome challenges and stay motivated. Teachers use analytics to track progress and adjust their methods, ensuring that no student is left behind.\r\n\r\nBusinesses leverage AI for data-driven decision-making, customer service, and supply chain optimization. Predictive analytics help companies anticipate market trends, while chatbots and virtual agents provide instant support. AI also plays a crucial role in cybersecurity, detecting threats and responding to incidents faster than ever before.\r\n\r\nAs AI’s influence grows, ethical considerations have become central to its development and deployment. Policymakers, technologists, and communities collaborate to address issues like bias, transparency, and privacy. The focus is on building trustworthy AI systems that respect human values, ensuring that technological progress benefits society as a whole.','<img class="showcase-teaser-image" src="/showcase-images/ai.jpg" alt="A robotic hand reaching towards an artificial intelligence network" width="240" height="135" style="position:absolute;left:0;top:0;display:block;width:240px;height:135px;margin:0;object-fit:cover">Artificial intelligence has become an essential part of everyday life, seamlessly embedded in homes, workplaces, and public spaces. Smart assistants, powered by advanced natural language processing, understand context and intent, making interactions more intuitive and productive. AI-driven automation handles routine tasks, freeing people to focus on creativity and problem-solving.\r\n\r','',UNIX_TIMESTAMP(),1),
    (2,2,1,'The enduring magic of Glastonbury','<p><img src="/showcase-images/glastonbury.jpg" alt="Aerial view of Glastonbury Festival at Worthy Farm" width="1200" height="675" style="display:block;max-width:100%;height:auto;margin-bottom:1.5em"></p>Glastonbury delivered another unforgettable chapter in the festival’s storied history, drawing music lovers from around the globe to Somerset’s iconic Worthy Farm. Each edition was marked by a diverse and electrifying lineup, with headline performances from both legendary acts and rising stars. The Pyramid Stage saw a triumphant return of classic rock icons, while the Other Stage pulsed with the energy of cutting-edge electronic and hip-hop artists, ensuring there was something for every musical taste.\r\n\r\nBeyond the music, Glastonbury continued its tradition of championing sustainability and community spirit. Festival organizers introduced new eco-friendly initiatives, including expanded recycling programs and innovative renewable energy solutions powering much of the site. Attendees embraced these efforts, making the festival one of the greenest yet.\r\n\r\nArt installations and immersive experiences dotted the landscape, transforming fields into vibrant galleries and interactive playgrounds. Workshops, talks, and wellness activities offered festival-goers opportunities for reflection and connection, reinforcing Glastonbury’s reputation as more than just a music festival—it’s a celebration of creativity, activism, and togetherness.\r\n\r\nAs the sun set on another magical weekend, Glastonbury left attendees with lasting memories and a renewed sense of hope, proving once again why it remains the world’s most beloved festival.','<img class="showcase-teaser-image" src="/showcase-images/glastonbury.jpg" alt="Aerial view of Glastonbury Festival at Worthy Farm" width="240" height="135" style="position:absolute;left:0;top:0;display:block;width:240px;height:135px;margin:0;object-fit:cover">Glastonbury delivered another unforgettable chapter in the festival’s storied history, drawing music lovers from around the globe to Somerset’s iconic Worthy Farm. Each edition was marked by a diverse and electrifying lineup, with headline performances from both legendary acts and rising stars. The Pyramid Stage saw a triumphant return of classic rock icons, while the Other Stage pulsed with the energy of cutting-edge electronic and hip-hop artists, ensuring there was something for every musical taste.\r\n\r','',UNIX_TIMESTAMP(),1);


INSERT INTO `variable` VALUES ('clean_url', 's:1:\"1\";');

INSERT INTO `node` VALUES
    (3,3,'story','Arsenal''s return to the summit',1,1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),2,1,0,0),
    (4,4,'story','The global rise of Nollywood',1,1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),2,1,0,0),
    (5,5,'story','Poland''s transformation into a European leader',1,1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),2,1,0,0);

INSERT INTO `node_revisions` VALUES
    (3,3,1,'Arsenal''s return to the summit','<p><img src="/showcase-images/arsenal-champs-2026.jpg" alt="Arsenal players celebrating with the Premier League trophy" width="1200" height="675" style="display:block;max-width:100%;height:auto;margin-bottom:1.5em"></p>Arsenal won the 2025/2026 Premier League and ended a 22-year wait for the championship. Years of investment in young players, recruitment, and a clear identity produced a team capable of sustaining a challenge.\r\n\r\nThe side combined disciplined possession with aggressive pressing and a defence built to control matches. Leaders guided a core that had developed together, while competition for places ensured injuries did not derail the campaign.\r\n\r\nThe title reflected the bond between team and supporters. Arsenal returned to the summit through planning, tactical evolution, and faith in a group that turned promise into achievement.','<img class="showcase-teaser-image" src="/showcase-images/arsenal-champs-2026.jpg" alt="Arsenal players celebrating with the Premier League trophy" width="240" height="135" style="position:absolute;left:0;top:0;display:block;width:240px;height:135px;margin:0;object-fit:cover">Arsenal won the 2025/2026 Premier League and ended a 22-year wait through patient rebuilding, tactical clarity, and a squad ready for a title race.','',UNIX_TIMESTAMP(),1),
    (4,4,1,'The global rise of Nollywood','<p><img src="/showcase-images/nollywood.jpg" alt="Nollywood sign and Nigerian flag on a sunlit hillside" width="1200" height="675" style="display:block;max-width:100%;height:auto;margin-bottom:1.5em"></p>Nollywood has grown from a resourceful home-video industry into one of the world’s most energetic centres of film and television. Early filmmakers worked with limited budgets and direct distribution, yet created stories audiences recognised immediately.\r\n\r\nFilms circulated across Africa and the diaspora, giving viewers characters, languages, and settings often absent from imported entertainment. The industry created opportunities for actors, writers, technicians, designers, musicians, and entrepreneurs.\r\n\r\nDigital production and streaming expanded Nollywood’s reach. Larger budgets and international partnerships now sit alongside its independent sector. Local stories continue to travel far beyond Nigeria.','<img class="showcase-teaser-image" src="/showcase-images/nollywood.jpg" alt="Nollywood sign and Nigerian flag on a sunlit hillside" width="240" height="135" style="position:absolute;left:0;top:0;display:block;width:240px;height:135px;margin:0;object-fit:cover">Nollywood has grown from a resourceful home-video industry into one of the world’s most energetic centres of film and television.','',UNIX_TIMESTAMP(),1),
    (5,5,1,'Poland''s transformation into a European leader','<p><img src="/showcase-images/poland-warsaw.jpg" alt="Warsaw Old Town and Castle Square in Poland" width="1200" height="675" style="display:block;max-width:100%;height:auto;margin-bottom:1.5em"></p>Since the fall of communism, Poland has undergone one of Europe’s most significant transformations. The transition from central planning released entrepreneurial energy and connected businesses with international markets.\r\n\r\nEuropean Union membership accelerated the process. Investment in transport, cities, universities, and digital infrastructure improved connections, while Polish companies became important parts of European supply chains.\r\n\r\nPoland’s population, strategic location, and commitment to regional security increased its influence. Challenges remain, but Poland has emerged as a resilient economy and a leading state whose choices will help define Europe’s future.','<img class="showcase-teaser-image" src="/showcase-images/poland-warsaw.jpg" alt="Warsaw Old Town and Castle Square in Poland" width="240" height="135" style="position:absolute;left:0;top:0;display:block;width:240px;height:135px;margin:0;object-fit:cover">Since the fall of communism, Poland has transformed its economy and become an increasingly influential member of the European Union.','',UNIX_TIMESTAMP(),1);
