#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    cms-20-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^cms-20\.ddev\.site$`)
      
      service: "cms-20-web-80"
      tls: false
      # middlewares:
      #   - "cms-20-redirectHttps"
    cms-20-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^cms-20\.ddev\.site$`)
      
      service: "cms-20-web-8025"
      tls: false
      # middlewares:
      #   - "cms-20-redirectHttps"
    cms-20-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^cms-20\.ddev\.site$`)
      
      service: "cms-20-xhgui-80"
      tls: false
      # middlewares:
      #   - "cms-20-redirectHttps"
    
    
    
    cms-20-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^cms-20\.ddev\.site$`)
      
      service: "cms-20-web-80"
      
      tls: true
      
    cms-20-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^cms-20\.ddev\.site$`)
      
      service: "cms-20-web-8025"
      
      tls: true
      
    
    cms-20-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^cms-20\.ddev\.site$`)
      
      service: "cms-20-xhgui-80"
      
      tls: true
      
    

  middlewares:
    cms-20-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    cms-20-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-cms-20-web:80
        
    cms-20-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-cms-20-web:8025
        
    
    
    cms-20-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-cms-20-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/cms-20.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/cms-20.key